feature
YakovMorkovkin/java-explore-with-me pull request #10
Opened 2023-04-26 18:21 UTC by YakovMorkovkin

2023-04-27 06:38 UTC, krylov-sergey-sergeevich requested changes
Привет

1) Логи в контроллерах
2) Небольшие правки по заметкам

Буду ждать с правками =)

2023-04-27 06:38 UTC, krylov-sergey-sergeevich commented on ewm/src/main/java/ru/practicum/comment/controller/CommentControllerPrivate.java
> +public class CommentControllerPrivate {
А нет ли желания сделать метод который получает много комментариев по userID и eventId

2023-04-27 06:38 UTC, krylov-sergey-sergeevich commented on ewm/src/main/java/ru/practicum/comment/controller/CommentControllerPrivate.java
> +public class CommentControllerPrivate {
update метода как будто не хватает

2023-04-27 06:38 UTC, krylov-sergey-sergeevich commented on ewm/src/main/java/ru/practicum/comment/controller/CommentControllerPublic.java
> +public class CommentControllerPublic {
Метод для получения 1 комментария был бы кстати

2023-04-27 11:49 UTC, YakovMorkovkin commented on ewm/src/main/java/ru/practicum/comment/controller/CommentControllerPublic.java
> +public class CommentControllerPublic {
добавил

2023-04-27 11:49 UTC, YakovMorkovkin commented on ewm/src/main/java/ru/practicum/comment/controller/CommentControllerPrivate.java
> +public class CommentControllerPrivate {
добавил

2023-04-28 04:56 UTC, krylov-sergey-sergeevich approved these changes
Привет, все хорошо - зачет

2023-05-11 17:14 UTC, merged