main service
YakovMorkovkin/java-explore-with-me pull request #9
Opened 2023-04-21 20:04 UTC by YakovMorkovkin

2023-04-22 20:15 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохо, давай обсудим детали некоторые и будет зачет

2023-04-22 20:15 UTC, krylov-sergey-sergeevich commented on ewm/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
`<version>${project.version}</version>`

2023-04-22 20:15 UTC, krylov-sergey-sergeevich commented on ewm/pom.xml
> +            <scope>compile</scope>
эта строка разве нужна?

2023-04-22 20:15 UTC, krylov-sergey-sergeevich commented on ewm/src/main/java/ru/practicum/category/dao/CategoryRepository.java
> +    List<Category> findWithParams(Long from, Long size);
А почему spring data page не воспользовался?

2023-04-22 20:15 UTC, krylov-sergey-sergeevich commented on ewm/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        startTime = now.plusHours(2);
Зачем так?

2023-04-23 06:22 UTC, YakovMorkovkin commented on ewm/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
поправил

2023-04-23 06:23 UTC, YakovMorkovkin commented on ewm/pom.xml
> +            <scope>compile</scope>
это импорт через Alt+Enter, IDEA(она сама добавляет)  )), убрал

2023-04-23 06:27 UTC, YakovMorkovkin commented on ewm/src/main/java/ru/practicum/category/dao/CategoryRepository.java
> +    List<Category> findWithParams(Long from, Long size);
Если использовать JPQL, то OFFSET,LIMIT не поддерживается, а в ТЗ указано что выборка должна формироваться после пропуска OFFSET элементов. А если через pageable реализовывать то приходится лишние данные выдергивать.

2023-04-23 06:29 UTC, YakovMorkovkin commented on ewm/src/main/java/ru/practicum/category/model/Category.java
> +    private String name;
поправил

2023-04-23 06:31 UTC, YakovMorkovkin commented on ewm/src/main/java/ru/practicum/category/service/CategoryService.java
> +@Validated
я её вынес в сервисный слой руководствовался этими соображениями
- Сервисы вызывают друг друга. Если сделать всю валидацию на контроллерах, то один сервис сможет передавать невалидные параметры в другой.
- Валидация в репозиторном слое означает, что бизнес-код работал с потенциально невалидными объектами, что может привести к непредвиденным ошибкам. И не у всех сервисов есть этот слой.
- Иногда ваши сервисы взаимодействиую с клиентами не только через контроллеры, что также может привести к работе с невалидными объектами в бизнесовом слое.

2023-04-23 07:28 UTC, YakovMorkovkin commented on ewm/src/main/java/ru/practicum/event/dto/outside/EventFullDto.java
> +    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
есть ) это была хорошая мысль которая в процессе забылась ) поправил

2023-04-23 07:36 UTC, YakovMorkovkin commented on ewm/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +                .timestamp(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")))
сделал

2023-04-23 07:44 UTC, YakovMorkovkin commented on ewm/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +                .timestamp(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")))
вынес

2023-04-23 07:45 UTC, YakovMorkovkin commented on ewm/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        startTime = now.plusHours(2);
действительно какая-то бессмысленная фигня ))) заработался видимо в тот вечер

2023-04-24 08:59 UTC, krylov-sergey-sergeevich approved these changes
Привет, зачет!

2023-04-24 09:05 UTC, merged